### ISSUE TITLE
General Feedback Card

### ISSUE THREAD

**Issue by andela-anandaa** [manuellah/bc-9-twitter-sentiment-app#8]
I've created this card to use for my general feedback that is not in particular to one story/card.

**Comment by andela-anandaa** [comment]
**Project Management**
- You've not done a good job on Project Management. As it stands now, you only have 2 feature cards. Is this all that the project is about?

**Comment by manuellah** [comment]
Yeah, they are the major functionality of the app

**Comment by manuellah** [comment]
but will be adding new features after creating the minimal working product, using the agile methodology.
